{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "fvcsh34bqzhkxpsyzoc7kxwbzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.4.0.jar",
          "url": "kriess-0.4.0.jar",
          "size": 55293,
          "sha512": "c541862a5b37a5eac675f0a76df4b59bc590f4b842c8475cdce480c01bfa5350e7fc0c0d294493b87ded1f86480fab3534fece57bae47a39cf4522bd6a1fe009",
          "sha256": "05983a21d1c197b3739c0dfa69ec6fcae73823bb443e7779c89b4ab2a4dd78c9",
          "sha1": "6eb12a036ed69d72ccca3ccd91e6fde6e5fb41e9",
          "md5": "ee9317f18e5183245dd2f929565bf8f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.4.0.jar",
          "url": "kriess-0.4.0.jar",
          "size": 55293,
          "sha512": "c541862a5b37a5eac675f0a76df4b59bc590f4b842c8475cdce480c01bfa5350e7fc0c0d294493b87ded1f86480fab3534fece57bae47a39cf4522bd6a1fe009",
          "sha256": "05983a21d1c197b3739c0dfa69ec6fcae73823bb443e7779c89b4ab2a4dd78c9",
          "sha1": "6eb12a036ed69d72ccca3ccd91e6fde6e5fb41e9",
          "md5": "ee9317f18e5183245dd2f929565bf8f1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.4.0-all.jar",
          "url": "kriess-0.4.0-all.jar",
          "size": 19038995,
          "sha512": "b3d6b1e98f187682b04947a5f6d76aff3f4f00611f5bd704eae7dc7e03e558263a5c8cde00b37d92289e08d80738179b663cd11d3450472e6808096208dab794",
          "sha256": "c8f156ef92101af16e1f83b04d84ca44786fee8167c8126882e5bae65ee8e524",
          "sha1": "e254b058ce9b39e78246729cc4e9bf279b365c50",
          "md5": "f44ada6b1cc9eb60a914d1e98d040387"
        }
      ]
    }
  ]
}
