{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "s577n34t3ja4jkpykm35lndzhq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.3.jar",
          "url": "kriess-0.5.3.jar",
          "size": 55327,
          "sha512": "c6f69bc1b916462828acb15c0c747515ae01daa25e07138c6e37621bd789fb4db067065b78a79e3ba023cbb62261f9b1e5f8945146139fa1e62a308f0215ccc5",
          "sha256": "1bacf674e338f91e424cede8bd22550570f9e3ee225b4b70c3c7d774fb06bc05",
          "sha1": "43732c483c3f0e38f63ece4f99033b77dc682973",
          "md5": "c2b3b8a0074a664eb6f0edfff1c43e9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.3.jar",
          "url": "kriess-0.5.3.jar",
          "size": 55327,
          "sha512": "c6f69bc1b916462828acb15c0c747515ae01daa25e07138c6e37621bd789fb4db067065b78a79e3ba023cbb62261f9b1e5f8945146139fa1e62a308f0215ccc5",
          "sha256": "1bacf674e338f91e424cede8bd22550570f9e3ee225b4b70c3c7d774fb06bc05",
          "sha1": "43732c483c3f0e38f63ece4f99033b77dc682973",
          "md5": "c2b3b8a0074a664eb6f0edfff1c43e9c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.5.3-all.jar",
          "url": "kriess-0.5.3-all.jar",
          "size": 19039029,
          "sha512": "8f597a0e6e09947abcae9ebd29b466b46259df18c505fdf5f8cfe44be7e82dcf286dc1032c982345e2c476a83615d3f9737ed1f44fec1b45bd12e95511fcdd0a",
          "sha256": "b07b8f232eaf838b3767d0184f9ebdddd6abd8b5b9c4295f0ff3ed18d29f98a2",
          "sha1": "5ead217e75f9d0191b79dbc5f2963d12189f33e8",
          "md5": "b4748462259edc7286bc2cfa7f9022c9"
        }
      ]
    }
  ]
}
