{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "jtrbdwbnxnh4npnfpyudh7de3i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.9.0.jar",
          "url": "kriess-0.9.0.jar",
          "size": 87026,
          "sha512": "e28f0079cd1241405b06f2e6286062f99409db260b977dc113e71e91ce3da243d8a70b1feae71ace6499def18c14db33f8dc2c8ddca8b3a31c9ddc753ab13a4e",
          "sha256": "dbdda7a63ef22610ffd32ec171dabea0df808f1c5f9924c930d1c79a5705f5ec",
          "sha1": "e3feb8aa73743111e63faa5a20bbafcf04c5131e",
          "md5": "5b80a77b75d4005dae5a010711861041"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.9.0.jar",
          "url": "kriess-0.9.0.jar",
          "size": 87026,
          "sha512": "e28f0079cd1241405b06f2e6286062f99409db260b977dc113e71e91ce3da243d8a70b1feae71ace6499def18c14db33f8dc2c8ddca8b3a31c9ddc753ab13a4e",
          "sha256": "dbdda7a63ef22610ffd32ec171dabea0df808f1c5f9924c930d1c79a5705f5ec",
          "sha1": "e3feb8aa73743111e63faa5a20bbafcf04c5131e",
          "md5": "5b80a77b75d4005dae5a010711861041"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.9.0-all.jar",
          "url": "kriess-0.9.0-all.jar",
          "size": 20743997,
          "sha512": "687ab7ac33a846df4483ec5d032db55109310761223b3afc15fc237e2da1902edacec38264924cd82915e7ae492c0a390cdb13452be44966be3d73f52388908e",
          "sha256": "d3c7f86424c51a6773cc8cd228ba2d89b3cf0351c6fc2bc19b72eec9a39fd6a9",
          "sha1": "202b1fc8136f1158f96d5cb20dd0e479a946c5b1",
          "md5": "a1d026ce10ee6c0608857a8b9414ecd8"
        }
      ]
    }
  ]
}
