{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.12.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "2dqh5z3v65a4np4er4orcikg2e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.12.3.jar",
          "url": "kriess-0.12.3.jar",
          "size": 103017,
          "sha512": "a60bba9a1cc87d3a4a8dbf24c88681c7c31d828fa3dbdcc3da146670af4fcc08e89ede59a39e034a10f908c94f30abc7dd2969ba5f585c4ced77b1891b50b90f",
          "sha256": "26473f47d65f1bdf6e25ed0ae31918c1587d398d1b207a0ccd285b65d206e115",
          "sha1": "ee8c61c921be2d76a4d75b4c42c0f80c4544664e",
          "md5": "9e10329166663032d8d8d3239b054ba6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.12.3.jar",
          "url": "kriess-0.12.3.jar",
          "size": 103017,
          "sha512": "a60bba9a1cc87d3a4a8dbf24c88681c7c31d828fa3dbdcc3da146670af4fcc08e89ede59a39e034a10f908c94f30abc7dd2969ba5f585c4ced77b1891b50b90f",
          "sha256": "26473f47d65f1bdf6e25ed0ae31918c1587d398d1b207a0ccd285b65d206e115",
          "sha1": "ee8c61c921be2d76a4d75b4c42c0f80c4544664e",
          "md5": "9e10329166663032d8d8d3239b054ba6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.12.3-all.jar",
          "url": "kriess-0.12.3-all.jar",
          "size": 20859447,
          "sha512": "be49f5748321c225c25d49efde0a951f64cfb54f52ec73d79f755dd25a8f3d0c6554a62a8ecbac50a67ef2f93faab81cff07ca12a377e09a9e95836048fc4e68",
          "sha256": "92506668b787ad6eee46ef4b7534f907b788dd529f81ab315820ae3dfa24af99",
          "sha1": "1e9b9c5af6c75027f6d2c0ba40094636e9336683",
          "md5": "fd1e78c2a89fa86df4b6ed1b39bbfbd4"
        }
      ]
    }
  ]
}
