{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "3ns7n75j25dhpmurd527pgkolq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.13.1.jar",
          "url": "kriess-0.13.1.jar",
          "size": 103281,
          "sha512": "1582538ba8b325ebb94dbba2cdce7463c20ea663662c51268bdd8f4d15d008a7f687266963654f4c6e40b0a92792a8df0316d8a6bcf00d1e8cfebd61f8781a36",
          "sha256": "35c87da20ba2e0536b4901b8bcc2aaa93fa3eb89687cc2bb4498610b11c655b8",
          "sha1": "5bbfd420c30a9de13d5bd1bd21005419f0333c5e",
          "md5": "0aed9f34e8f1820341cca0462807c2d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.13.1.jar",
          "url": "kriess-0.13.1.jar",
          "size": 103281,
          "sha512": "1582538ba8b325ebb94dbba2cdce7463c20ea663662c51268bdd8f4d15d008a7f687266963654f4c6e40b0a92792a8df0316d8a6bcf00d1e8cfebd61f8781a36",
          "sha256": "35c87da20ba2e0536b4901b8bcc2aaa93fa3eb89687cc2bb4498610b11c655b8",
          "sha1": "5bbfd420c30a9de13d5bd1bd21005419f0333c5e",
          "md5": "0aed9f34e8f1820341cca0462807c2d6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.13.1-all.jar",
          "url": "kriess-0.13.1-all.jar",
          "size": 20859711,
          "sha512": "0ecf81f627068f799876cf46a42787791309a9e83da3c18c1345876b36150ee9e3f994c5edeb54ba7b9542bc51d17741902dc9556c16c0024f8c15e888c9d9de",
          "sha256": "d179c685000ba3313f9243f54047cb6e62014e5b601dda1aa28642624e783be0",
          "sha1": "9f5ab275034d6e877a5eb4c4e7506c20ecc5c3d8",
          "md5": "98412883a8d9bd3b51260ef2242791e9"
        }
      ]
    }
  ]
}
