{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.12.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6ekqsmxjjrhqze52tjsw2hxppe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.12.4.jar",
          "url": "kriess-0.12.4.jar",
          "size": 103077,
          "sha512": "53132b31547395ffefb882375d70af89ad70e8f2223deca37894dd8ecd4fd813e8cebb683ed4d18360d7de81d493dfd6fd5add68641d8008d408ad3d03da3d4d",
          "sha256": "78a80f2932eda474228b93b252647dc9b3df219b576a306a3ce52b1c2b15b5b0",
          "sha1": "f0bc1af50e6db8e20823a4e5c3285cc4b2ef5e6f",
          "md5": "07520156493a8a62dd21573005141cee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.12.4.jar",
          "url": "kriess-0.12.4.jar",
          "size": 103077,
          "sha512": "53132b31547395ffefb882375d70af89ad70e8f2223deca37894dd8ecd4fd813e8cebb683ed4d18360d7de81d493dfd6fd5add68641d8008d408ad3d03da3d4d",
          "sha256": "78a80f2932eda474228b93b252647dc9b3df219b576a306a3ce52b1c2b15b5b0",
          "sha1": "f0bc1af50e6db8e20823a4e5c3285cc4b2ef5e6f",
          "md5": "07520156493a8a62dd21573005141cee"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.12.4-all.jar",
          "url": "kriess-0.12.4-all.jar",
          "size": 20859507,
          "sha512": "17c93d23f061ac68cc23db2b0760abc32403f0380078f2dcb6abe78a7756f9ac4c18ac1ab406b86acf4777f93620215f4b77206edea0388ffa8d5fa2a8211989",
          "sha256": "156ca3a6b913d865e0b05343e732e7789e632800c8f93e60985ab7b457699aa0",
          "sha1": "88b5428d5069bc924ea0463a9587d31dc5ac0221",
          "md5": "10bdeeca588a8a5269166e10df38acde"
        }
      ]
    }
  ]
}
