{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "vjdxdm2qrna3pibmkxnldhnf4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.9.2.jar",
          "url": "kriess-0.9.2.jar",
          "size": 86982,
          "sha512": "3a1ef47b464ad2fbca99cba72472173a2ebf221981cbb9563940d6aefc8b6afee8356bb243a4797db821bb3c1f146ff0569ad2284b7ac522b4aec353c8fb728c",
          "sha256": "e329479592991e56fd85f7ed5152dcb8866cda5e48dcd7e1d2c9c254b70044ba",
          "sha1": "6dab82b1a2d5e5bc4326da03ee7f94bf55a6e43e",
          "md5": "15a66bbae9c02931efe7dafe4b6f9899"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.9.2.jar",
          "url": "kriess-0.9.2.jar",
          "size": 86982,
          "sha512": "3a1ef47b464ad2fbca99cba72472173a2ebf221981cbb9563940d6aefc8b6afee8356bb243a4797db821bb3c1f146ff0569ad2284b7ac522b4aec353c8fb728c",
          "sha256": "e329479592991e56fd85f7ed5152dcb8866cda5e48dcd7e1d2c9c254b70044ba",
          "sha1": "6dab82b1a2d5e5bc4326da03ee7f94bf55a6e43e",
          "md5": "15a66bbae9c02931efe7dafe4b6f9899"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.9.2-all.jar",
          "url": "kriess-0.9.2-all.jar",
          "size": 20743953,
          "sha512": "c8a02d1a26835804bed98411014427fdadfb216d281545c9edec6a437a08f91924f7e99ab5f6757942bb86af647247beccd2bc3df430c703021f2717f63a56e3",
          "sha256": "e29b96496b54500fd2198e54d4eea85b8db503e017972c6d82fa40777d883630",
          "sha1": "094438ccd67a507bf284603f31140bab86a3444d",
          "md5": "c85acf268f3af7b8bf712915cc2e5cf3"
        }
      ]
    }
  ]
}
