{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "pj6th52dcvdghcdcmpfstrtajq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.4.jar",
          "url": "kriess-0.5.4.jar",
          "size": 55361,
          "sha512": "d91eac63d790a9a97b1e3808df97f855d0e1cc7ee7bf880eb7f4dcab73b17c2c7ea59a2ab357ba2458629f2a8f7861c8160110d50f270f92455cbcc1da590236",
          "sha256": "9d04ed743c705573650e2f9bb370e71417ebcbff5e25a1c838ee625df053fd99",
          "sha1": "1a20a6636912846ab958a5eefcc2b86a69894ff8",
          "md5": "e8f72c7f16f2e94620ab756628b80f0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.4.jar",
          "url": "kriess-0.5.4.jar",
          "size": 55361,
          "sha512": "d91eac63d790a9a97b1e3808df97f855d0e1cc7ee7bf880eb7f4dcab73b17c2c7ea59a2ab357ba2458629f2a8f7861c8160110d50f270f92455cbcc1da590236",
          "sha256": "9d04ed743c705573650e2f9bb370e71417ebcbff5e25a1c838ee625df053fd99",
          "sha1": "1a20a6636912846ab958a5eefcc2b86a69894ff8",
          "md5": "e8f72c7f16f2e94620ab756628b80f0e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.5.4-all.jar",
          "url": "kriess-0.5.4-all.jar",
          "size": 19039063,
          "sha512": "363abdf3b1395b458b349b497a21915805320fc8b8392d555a53ef48fcff1c8cf9afd954b15df26c74ddb5bd2a8add6581aafdf27dadd4f61f488d4589144530",
          "sha256": "d12cd1c0bd1883d8232dc489d31c027a9bae54b59644b075b23b145a9b7ee48b",
          "sha1": "c893a38f09709c27617631f29282ea728375f12e",
          "md5": "d3c9255c47517891401be41eafb249d1"
        }
      ]
    }
  ]
}
