{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "vg52zrdx3jfy3aoylpyqrllxi4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.0.jar",
          "url": "kriess-0.5.0.jar",
          "size": 55352,
          "sha512": "5c29c42a0d787ea7829d5216d7c38373d55db2ffcbd5588c612c34ee63e4718c5348ed99ca18d3e4ad30e5780736d2d8cfa2047bdf29a8d01b296950fc0cdf7c",
          "sha256": "948af0c67b53edef6452e2c5536384a3c0acf67fdb51052b5102c8c6437091ec",
          "sha1": "9a43f31972a1c9f402cebe27d2836c5d861af95d",
          "md5": "909f6e260fe54b7de3e7b80c9164e0af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.0.jar",
          "url": "kriess-0.5.0.jar",
          "size": 55352,
          "sha512": "5c29c42a0d787ea7829d5216d7c38373d55db2ffcbd5588c612c34ee63e4718c5348ed99ca18d3e4ad30e5780736d2d8cfa2047bdf29a8d01b296950fc0cdf7c",
          "sha256": "948af0c67b53edef6452e2c5536384a3c0acf67fdb51052b5102c8c6437091ec",
          "sha1": "9a43f31972a1c9f402cebe27d2836c5d861af95d",
          "md5": "909f6e260fe54b7de3e7b80c9164e0af"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.5.0-all.jar",
          "url": "kriess-0.5.0-all.jar",
          "size": 19039054,
          "sha512": "bf368e3948673bf75ebbe29e0137f28a7eb45d179a39debcd20a2f002447a66bb5888a39a7e80bfcda4072f2c4e67d5714f6de5db8cfb81ba3f816bc46c2a653",
          "sha256": "9b7950c0525e9ff7bdf344efd2c72e498f4d9835f55513aeb292c054bf115d71",
          "sha1": "5daddf06621666b01b152c995ca17240d33b4843",
          "md5": "c94a18ddc2fc887db0e01f11e57c46d4"
        }
      ]
    }
  ]
}
