{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vih6muggnbag5mlvvbuewx7f64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.13.0.jar",
          "url": "kriess-0.13.0.jar",
          "size": 103175,
          "sha512": "7cd999fd1f727016cbd0748f18129f0a57503abdfd804e70de510acebf03b3d776b1a2dd70c1b3b9e032384dc860627b74c6791dfeae866d6769deae32b4e420",
          "sha256": "2de8e8c70a366c480fb7c3dc4f858ea25b03741518cc8ff6c76f2c92c3b424cd",
          "sha1": "a7f064d1e41e0c668ad75778afe1d64e2cc5769d",
          "md5": "25f5b52c83cc2e139aa2cfa157b22627"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.13.0.jar",
          "url": "kriess-0.13.0.jar",
          "size": 103175,
          "sha512": "7cd999fd1f727016cbd0748f18129f0a57503abdfd804e70de510acebf03b3d776b1a2dd70c1b3b9e032384dc860627b74c6791dfeae866d6769deae32b4e420",
          "sha256": "2de8e8c70a366c480fb7c3dc4f858ea25b03741518cc8ff6c76f2c92c3b424cd",
          "sha1": "a7f064d1e41e0c668ad75778afe1d64e2cc5769d",
          "md5": "25f5b52c83cc2e139aa2cfa157b22627"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.13.0-all.jar",
          "url": "kriess-0.13.0-all.jar",
          "size": 20859605,
          "sha512": "0e5510322a1cd7e204c4a76deb710c45bcac01f5e17df6f5207cec7ad52a6ad7045d8e46b2c4b3dbee37b809a84437cbf3eab38d7fb3177176d21029096b40e0",
          "sha256": "b6afde6a0093dc52e7b0160636cfabf54f2ad1e7418ee74a9706989bad1e7aa4",
          "sha1": "f7f34b033c219a745ea706072e53d88d781570b5",
          "md5": "bb1b94e4ed229d4296bda3b76a7b187d"
        }
      ]
    }
  ]
}
