{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "w7a43vefzzbkrcjz66sfw54zb4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.13.0.jar",
          "url": "kriess-0.13.0.jar",
          "size": 103218,
          "sha512": "9770bf5c60b8b7837424a98a591db21aab8570862c32be1a4494e8991331224f8f68bff32f06d613bd2a0dd69be915b5f12f1cd5085993a576222eab661fa82d",
          "sha256": "f1df9a90e6e802cb1c9ea4dce95e5f9e518ccfd166428f3fc839c961d1f439a7",
          "sha1": "27ac8b3289ce8291d1df471815d36d469d0f69b3",
          "md5": "02c11aa64e79b4da382e52bf56df35df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.13.0.jar",
          "url": "kriess-0.13.0.jar",
          "size": 103218,
          "sha512": "9770bf5c60b8b7837424a98a591db21aab8570862c32be1a4494e8991331224f8f68bff32f06d613bd2a0dd69be915b5f12f1cd5085993a576222eab661fa82d",
          "sha256": "f1df9a90e6e802cb1c9ea4dce95e5f9e518ccfd166428f3fc839c961d1f439a7",
          "sha1": "27ac8b3289ce8291d1df471815d36d469d0f69b3",
          "md5": "02c11aa64e79b4da382e52bf56df35df"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.13.0-all.jar",
          "url": "kriess-0.13.0-all.jar",
          "size": 20859648,
          "sha512": "4e107e17a1b50470dc4a72b31cac81fc34bcc6fc65d644df04674d61ef8730d4dcc5f9e04de46efbd0500c27a78e0d222c445a41d29c6923019dbdd1594eeea9",
          "sha256": "1474a234e7a4244296d0daae95d3e9468d2bbd09f8de11083a421cc67330ed32",
          "sha1": "a7aea8b4a2149d412f1eead563e8804043272f82",
          "md5": "cfe0017ca0a94c28761e0098dfbded0f"
        }
      ]
    }
  ]
}
