{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "pky76i4ixvbsvebe6ezumx3or4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.9.1.jar",
          "url": "kriess-0.9.1.jar",
          "size": 87045,
          "sha512": "d89082ef4b1fe6f0ea69fe2c8ee7fd3e35b667eebc2c4aefdee03a12f7b8ce91719805b3b817def4091422b3fcbe82915128b546fb4ab9cfe579adc4fe3fbd19",
          "sha256": "4df5c699944f68b4aa7ed9011576fb8fd855223126c1584f833e7b96e2f46935",
          "sha1": "0a09384c392471715375086786cbe50678adf745",
          "md5": "39087505f8ded2a58950253eb0f6793a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.9.1.jar",
          "url": "kriess-0.9.1.jar",
          "size": 87045,
          "sha512": "d89082ef4b1fe6f0ea69fe2c8ee7fd3e35b667eebc2c4aefdee03a12f7b8ce91719805b3b817def4091422b3fcbe82915128b546fb4ab9cfe579adc4fe3fbd19",
          "sha256": "4df5c699944f68b4aa7ed9011576fb8fd855223126c1584f833e7b96e2f46935",
          "sha1": "0a09384c392471715375086786cbe50678adf745",
          "md5": "39087505f8ded2a58950253eb0f6793a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.9.1-all.jar",
          "url": "kriess-0.9.1-all.jar",
          "size": 20744016,
          "sha512": "07d76eed344140e496ad38e01dfd4f2f40c7a91f084ea872ee85733cd8d9642c69c22aa0b99b9d31ba59df8e808d848fc8f05d34bbceda73c46c108931e43a37",
          "sha256": "ec9b5ef1f764fdf3d2f95b240cc9dc47f0db15ded0d3abcf6acaac812b7c11fd",
          "sha1": "1bf1c75bae2c0eae0e343bbcc4972b1300c1eaf0",
          "md5": "fadb3312b9954266195009ef19242f2c"
        }
      ]
    }
  ]
}
