{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.brettb",
    "module": "arrow",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "me.ialistannen",
          "module": "MiniNBT",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "arrow-0.0.1.jar",
          "url": "arrow-0.0.1.jar",
          "size": 67987,
          "sha512": "d4a0de99b276573d9ccd9a6a68310947f71fd2a12cdd3374bd4d3ab4b3e812207357dd382677f17eb4568671e40d08d08c82b9b3113dad0ed89b5eb50f0328b6",
          "sha256": "d27b373deda571158ed05c8c0c77937fc7b966f99619503f0a92fb0b3d72ff2b",
          "sha1": "264f92b1f3fa707362af5aee6420efcc2ffa60a6",
          "md5": "82765b4f9d84f0ce980576c6571485e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.cryptomorin",
          "module": "XSeries",
          "version": {
            "requires": "9.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "me.ialistannen",
          "module": "MiniNBT",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "arrow-0.0.1.jar",
          "url": "arrow-0.0.1.jar",
          "size": 67987,
          "sha512": "d4a0de99b276573d9ccd9a6a68310947f71fd2a12cdd3374bd4d3ab4b3e812207357dd382677f17eb4568671e40d08d08c82b9b3113dad0ed89b5eb50f0328b6",
          "sha256": "d27b373deda571158ed05c8c0c77937fc7b966f99619503f0a92fb0b3d72ff2b",
          "sha1": "264f92b1f3fa707362af5aee6420efcc2ffa60a6",
          "md5": "82765b4f9d84f0ce980576c6571485e1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arrow-0.0.1-all.jar",
          "url": "arrow-0.0.1-all.jar",
          "size": 5374926,
          "sha512": "4b932c4a999d657f10f70b526d526b4430895ef1eb249b4fef4f8e9f2099fb10d6d2bfe63e37c350b99f1c707b8ac6d77260c1015c118c5a45e89b3dc5564e6e",
          "sha256": "ee74f20ba6c7baa1f163a5fd410715d904906bb37056b55f5d1a7b3a53742ed2",
          "sha1": "471179f7d9fff8a7c713ce8457e1747fc5fce537",
          "md5": "fce7a6f0ac5951dc94a2df7a191bf8aa"
        }
      ]
    }
  ]
}
