{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "2kdxwkyogncgvbyxsicu22h2wu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.5.jar",
          "url": "kriess-0.5.5.jar",
          "size": 55361,
          "sha512": "a41bfe77fe25e1eb55c2d2539c5553851eafe2239fde1e70d962119ee89174aaf6596b81d8da4d4f29bf08aa0c199aaac485e83e63d2dc5a8d39cb3dc042e677",
          "sha256": "a91c8ad980236a89edfa5f4e37d200e87ac2f4ba09b69ea34bc0aa6154c4773d",
          "sha1": "56205dde96a250b431689c04d17b9ee87fef53e9",
          "md5": "cda2c4f7fe7a4273d9056afaf37fcca6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.5.jar",
          "url": "kriess-0.5.5.jar",
          "size": 55361,
          "sha512": "a41bfe77fe25e1eb55c2d2539c5553851eafe2239fde1e70d962119ee89174aaf6596b81d8da4d4f29bf08aa0c199aaac485e83e63d2dc5a8d39cb3dc042e677",
          "sha256": "a91c8ad980236a89edfa5f4e37d200e87ac2f4ba09b69ea34bc0aa6154c4773d",
          "sha1": "56205dde96a250b431689c04d17b9ee87fef53e9",
          "md5": "cda2c4f7fe7a4273d9056afaf37fcca6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.5.5-all.jar",
          "url": "kriess-0.5.5-all.jar",
          "size": 19039063,
          "sha512": "6fb88164da8e74c757833f8edbc7baf278a63f475cf62a4e08ad18831e4c69a7229528c2e2370bfd59900a297f4193dc9aefe8494cbfd2eafd3c778a27dacd28",
          "sha256": "1f5d77ab34cd0a132eaa29ae65c30f812f8ba6745851023a75387d6544b42310",
          "sha1": "eeb3ee135fa046d3c7ae6e1162537c3ff18bedff",
          "md5": "63166b7256d420a5817c7a7fe79b578f"
        }
      ]
    }
  ]
}
