{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "wyixqyutubayzcb2zxsyxgzzx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.1.0.jar",
          "url": "kriess-0.1.0.jar",
          "size": 27890,
          "sha512": "d7aaaf04aff6f05f40105f893c5f40e3d2425ff4ebe54493de37df8c9f5c073081334e321c43cfa89fd2a0f9c274dbc87de06fae9ffaaab93957b1f63198058e",
          "sha256": "3868592ba5f16af670a2795181228ac1127158d1bd2ad358a65b035a3ed0ec8a",
          "sha1": "a288dd6ccd788125f56f9fa83f2c222a76865bb8",
          "md5": "33d559ad9485ab3cd5be914c1aad9462"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.1.0.jar",
          "url": "kriess-0.1.0.jar",
          "size": 27890,
          "sha512": "d7aaaf04aff6f05f40105f893c5f40e3d2425ff4ebe54493de37df8c9f5c073081334e321c43cfa89fd2a0f9c274dbc87de06fae9ffaaab93957b1f63198058e",
          "sha256": "3868592ba5f16af670a2795181228ac1127158d1bd2ad358a65b035a3ed0ec8a",
          "sha1": "a288dd6ccd788125f56f9fa83f2c222a76865bb8",
          "md5": "33d559ad9485ab3cd5be914c1aad9462"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.1.0-all.jar",
          "url": "kriess-0.1.0-all.jar",
          "size": 8233959,
          "sha512": "63301f02597c190f9bb81bce5b1077908b3f95a8e14e888b0985117cdd0ae21ae587f674017409d5eaf8cca0f22b11f162e8ca9b2128c0eba88f95a8bfc01880",
          "sha256": "6405b2182ed3da68187e99e30fb977085daf764a23ba5482a460b6f58d2e8e59",
          "sha1": "6d414d538e7f1a9e06abd19efb0dec138159ae06",
          "md5": "a890740591cc9a4898fdc931971c532b"
        }
      ]
    }
  ]
}
