{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "dafozkcrmfezhhhnoauerrcbee"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.1.0.jar",
          "url": "kriess-0.1.0.jar",
          "size": 18974386,
          "sha512": "a923618d57be8c9bbd4e09e60ff6f8a8ff57c9c97da4331883bda0a4fd040efee3a8430a4f468adb8bd52a535db0ee8781a916c316d1ec100b69257afa22fa30",
          "sha256": "266376c68c87f791f2d4f7a1ac5325b7d8de2a7eb494631704c2a2bb0e137860",
          "sha1": "d4dc3404e78f798a0e0beb563b3d40ef2623fc0f",
          "md5": "64d4f34f9e1a350885877eafd14d0e36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.1.0.jar",
          "url": "kriess-0.1.0.jar",
          "size": 18974386,
          "sha512": "a923618d57be8c9bbd4e09e60ff6f8a8ff57c9c97da4331883bda0a4fd040efee3a8430a4f468adb8bd52a535db0ee8781a916c316d1ec100b69257afa22fa30",
          "sha256": "266376c68c87f791f2d4f7a1ac5325b7d8de2a7eb494631704c2a2bb0e137860",
          "sha1": "d4dc3404e78f798a0e0beb563b3d40ef2623fc0f",
          "md5": "64d4f34f9e1a350885877eafd14d0e36"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.1.0.jar",
          "url": "kriess-0.1.0.jar",
          "size": 18974386,
          "sha512": "a923618d57be8c9bbd4e09e60ff6f8a8ff57c9c97da4331883bda0a4fd040efee3a8430a4f468adb8bd52a535db0ee8781a916c316d1ec100b69257afa22fa30",
          "sha256": "266376c68c87f791f2d4f7a1ac5325b7d8de2a7eb494631704c2a2bb0e137860",
          "sha1": "d4dc3404e78f798a0e0beb563b3d40ef2623fc0f",
          "md5": "64d4f34f9e1a350885877eafd14d0e36"
        }
      ]
    }
  ]
}
