{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ecnm6wolcfezbgovat24bj44ye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.6.jar",
          "url": "kriess-0.5.6.jar",
          "size": 55359,
          "sha512": "1df04c13ad48d383435d2e079098cada357d31edb8c85d1d6a509ce2da6f20db21b76edb2707c38595e477896ff5263a0508151b810faaf6fb7ea570e5c559b5",
          "sha256": "f044f920913d4729b005d01e85e84dfc29a6c956b6ebb0f1e271847154c3bc79",
          "sha1": "ce70c64e10cb3e82e1ad871a549aa67b910f7f32",
          "md5": "132163c58fecb43da58f8902a3a85c91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_207"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.5.6.jar",
          "url": "kriess-0.5.6.jar",
          "size": 55359,
          "sha512": "1df04c13ad48d383435d2e079098cada357d31edb8c85d1d6a509ce2da6f20db21b76edb2707c38595e477896ff5263a0508151b810faaf6fb7ea570e5c559b5",
          "sha256": "f044f920913d4729b005d01e85e84dfc29a6c956b6ebb0f1e271847154c3bc79",
          "sha1": "ce70c64e10cb3e82e1ad871a549aa67b910f7f32",
          "md5": "132163c58fecb43da58f8902a3a85c91"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.5.6-all.jar",
          "url": "kriess-0.5.6-all.jar",
          "size": 19039061,
          "sha512": "625456d83eace04a3d9eae9bcf9bb739aba9f129749b1fbe7e6d13d99cc7de68f0e20a3f7401b5e8543caedc88a605969f621242caacf17173e6caca166fd2af",
          "sha256": "5bbeeeff23129f4767c1b95ff3b1b99136b183726f9923ea9dc196c6ab67b9d4",
          "sha1": "c17a538b456a106ddc08fdc4d6b8b340b723432b",
          "md5": "8fe160dd3c7a095eca5ae279c1199863"
        }
      ]
    }
  ]
}
