{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.junodevs.discord",
    "module": "kriess",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "6b73d6nx4necjnjpvdh3iv67jq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.8.0.jar",
          "url": "kriess-0.8.0.jar",
          "size": 86063,
          "sha512": "b6f59a44e8b2f5bc1800e5c7d5854247d14fccf613aac12ea6c74785fb3a46d22897c5c20140c2798e2250e42d87e115abd6e4b8986b308e2be88cefb238a9ca",
          "sha256": "1327b792cacfa9abee9c277319a4138b3a0fa9b2ff5100729c3216e675ac857f",
          "sha1": "4976245a5b1655bb249d5802810c52e2843cd873",
          "md5": "26ac93f3028e05cc3639effab5799535"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-jre"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "4.2.0_229"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "kriess-0.8.0.jar",
          "url": "kriess-0.8.0.jar",
          "size": 86063,
          "sha512": "b6f59a44e8b2f5bc1800e5c7d5854247d14fccf613aac12ea6c74785fb3a46d22897c5c20140c2798e2250e42d87e115abd6e4b8986b308e2be88cefb238a9ca",
          "sha256": "1327b792cacfa9abee9c277319a4138b3a0fa9b2ff5100729c3216e675ac857f",
          "sha1": "4976245a5b1655bb249d5802810c52e2843cd873",
          "md5": "26ac93f3028e05cc3639effab5799535"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kriess-0.8.0-all.jar",
          "url": "kriess-0.8.0-all.jar",
          "size": 20743034,
          "sha512": "62eb0cb6fc42bc9774aa37ee32e9b3859941445ca1b47096a668181066497a348dccbe2edb3b1e946f641c55b1a0a33fd6e07fc98e02a902c1a9450fd927e64c",
          "sha256": "f2dd9398e10abbcf9599938465b80250b8225df0168fd396c4a17baab45a1d08",
          "sha1": "0fce123b984f66e82996f8f100182d5ee17daf17",
          "md5": "66c7e5be2cc4a455936257667a897379"
        }
      ]
    }
  ]
}
